plugins {
	id 'java'

	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'

	id 'io.freefair.lombok' version "9.5.0"
}

version = project.mod_version
group = project.maven_group

repositories {
	maven {
		name "sylvielol"
		url "https://maven.sylvie.lol/releases"
	}
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	implementation "lol.sylvie.lauve.events:lauve-events:${project.lauve_events_version}"

	implementation "com.catppuccin:catppuccin-palette:2.0.3"
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}

// Run script
tasks.register('runScript', JavaExec) {
	classpath = sourceSets.main.runtimeClasspath
	mainClass = 'lol.sylvie.lauve.script.runtime.RuntimeEntrypoint'

	doFirst {
		if (!workingDir.exists()) {
			workingDir.mkdirs()
		}
	}
}

// Data generation
tasks.register('generateEditorData', JavaExec) {
	classpath = sourceSets.main.runtimeClasspath
	mainClass = 'lol.sylvie.lauve.script.datagen.ScriptDatagen'
	workingDir = file("$projectDir/web")

	doFirst {
		if (!workingDir.exists()) {
			workingDir.mkdirs()
		}
	}
}